### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by ghost** [danfickle/openhtmltopdf#921]
Does anyone know the status of this project, the last merges and release happened some time ago, and responses to issues from the maintainer have stopped also.

**Comment by fcorneli** [comment]
Related https://github.com/danfickle/openhtmltopdf/issues/839

**Comment by moreaki** [comment]
And https://github.com/danfickle/openhtmltopdf/issues/926

**Comment by costas80** [comment]
It would be such a shame if this project dies... It is by miles the best, free and open source library of it's kind for any kind of PDF creation needs.

Is there an "official" way to keep the repo alive without everyone making their own fork?

**Comment by kdhrubo** [comment]
Planning to fork, maintain, and enhance the project and also add API on top of it. Will wait for the maintainer to respond. Will start end of may summer.

**Comment by fcorneli** [comment]
Maybe create a ticket to see who is interested in helping out with the maintenance?

**Comment by moreaki** [comment]
> Planning to fork, maintain, and enhance the project and also add API on top of it. Will wait for the maintainer to respond. Will start end of may summer.

This is most commendable. 

Having been more or less involved in all sorts of Open-Source projects activities over the past 30+ years, I've often seen a lot of enthusiasm at the beginning of a project change. A project of this size and complexity will probably require a sizable investment of time from a team of dedicated volunteers. It's not just the maintenance of the project, it requires vision and an understanding of the user-base behind it. Some thoughts:

- Try to contact the original maintainer to figure out what his vision is regarding the project
- Propose a milestone outlook of what you want to do with the project over which time (looking at the issues and merge request gives you a good idea of the current pipeline of todos)
- Find volunteers with the respective profiles (tester, subject-matter experts, developers, integrators from industry, product managers), who are willing to invest a continuous reliable amount of time to this project.
- Collect further feedback by initiating an open discussion and inviting people to participate in the shaping of this project.
- Find business sponsors who might be willing to invest some of their resources (time, money, infrastructure) to support this valuable project.

With all the endeavors possible, I believe it's most helpful to try and contact the original maintainer and/or author of the project to work out together a healthy path for the project going forward. Because it's truly an important project for many people. Two of my companies are actually using this project as part of their technology stack for some of our products.

**Comment by VILLAN3LL3** [comment]
> * Try to contact the original maintainer to figure out what his vision is regarding the project

The maintainer has been contacted several times in other threads asking for feedback. Unfortunately without success so far. I am almost afraid that we will have to skip this step.

**Comment by chrylis** [comment]
@kdhrubo I am interested in potentially assisting in updates to this library. In particular, I would like to use it in conjunction with PDFBox 3.0, and I think it could be done reasonably easily.

**Comment by kdhrubo** [comment]
Sounds like a plan @chrylis. Will ping you here soon.

**Comment by kdhrubo** [comment]
Hi, who would like to join and take this project forward? Here is what I am thinking

1. Fork away given beloved @danfickle has not responded long or there is no status change. Also, I have not found him on Linkedin or other social portals either. 
2. Let's fork this library and keep all licenses and issues. 
3. Goal should be to solve the issues and review PRs and merge them initially. 
4. Upgrade dependencies and reduce any vulnerabilities
5. Add new feature requests based on community voting. 
6. Setup slack channel for project member discussion. 
7. Build a REST API on top of this library as a commercial offering to sustain this project as open source forever. 

Please share your thoughts and votes and we can take this forward. 

Regards ... dhrubo

**Comment by chrylis** [comment]
I am in general agreement, but since this project has been stale for a while, I suggest moving to a baseline of PDFBox 3 and cleanup as the first steps, and then retrofitting any outstanding PRs. Gitter might also be simpler than Slack, but I don't have a strong opinion there.

**Comment by MoxxiManagarm** [comment]
Let me first point out, I am very glad a team of very motivated developers aim to keep this project going. Chapeau.

How is the status of the fork? Is there a link? Do you need any kind of assist to get it started?


> Also, I have not found him on Linkedin or other social portals either.

* https://au.linkedin.com/in/daniel-fickling-18b466123?trk=people-guest_people_search-card
* I contacted the 2 developers who are mentioned as co-contributors, only to find out they have no contact to him and are not actually involved in the project. 
* I also found a website back then where I believed it is his website, but I can't find it again.

**Comment by VILLAN3LL3** [comment]
> How is the status of the fork? Is there a link? Do you need any kind of assist to get it started?

I would like to join the question

**Comment by Zefling** [comment]
Apache PDFBox 3.0.0 released 2023-08-17
https://pdfbox.apache.org/

**Comment by hughsimpson** [comment]
Ah, wish I'd found this issue before I opened [a pr to bump pdfbox](https://github.com/danfickle/openhtmltopdf/pull/941) - happy to help out if anyone wants to start a supported fork

**Comment by sadath42** [comment]
> Hi, who would like to join and take this project forward? Here is what I am thinking
> 
> 1. Fork away given beloved @danfickle has not responded long or there is no status change. Also, I have not found him on Linkedin or other social portals either.
> 2. Let's fork this library and keep all licenses and issues.
> 3. Goal should be to solve the issues and review PRs and merge them initially.
> 4. Upgrade dependencies and reduce any vulnerabilities
> 5. Add new feature requests based on community voting.
> 6. Setup slack channel for project member discussion.
> 7. Build a REST API on top of this library as a commercial offering to sustain this project as open source forever.
> 
> Please share your thoughts and votes and we can take this forward.
> 
> Regards ... dhrubo

Hi @kdhrubo 

Did you fork the library??
Looks like it is one of the few open source library which does html to pdf conversion.
Happy to help.

**Comment by imario42** [comment]
I've cloned this project to

https://github.com/imario42/openhtmltopdf

and just released a 1.1.3 version under my 
                <groupId>at.datenwort.openhtmltopdf</groupId>
group.
Might take a bit to show up in Maven Central.

Basically only Pdfbox 3 update and fixes to make the test run ok.

I have no specific plans to maintain this project I have to admit, but lets see what comes.

**Comment by MoxxiManagarm** [comment]
> I've cloned this project to
> 
> https://github.com/imario42/openhtmltopdf
> 
> and just released a 1.1.3 version under my at.datenwort.openhtmltopdf group. Might take a bit to show up in Maven Central.
> 
> Basically only Pdfbox 3 update and fixes to make the test run ok.
> 
> I have no specific plans to maintain this project I have to admit, but lets see what comes.

🥇 

This is so much appraciated. However, one of the most asked updates is to bump batik to remove some CVE's.
Would you mind to add another version with it updated? By now, batik is at 1.17, but in project it is still 1.14.

🙏🏻 

For further reference: https://github.com/danfickle/openhtmltopdf/pull/878

**Comment by imario42** [comment]
Sure! When I am back from vacation I will check that.

**Comment by enstulen** [comment]
> Planning to fork, maintain, and enhance the project and also add API on top of it. Will wait for the maintainer to respond. Will start end of may summer.

@kdhrubo Any updates on this?

**Comment by Digirik** [comment]
With @kdhrubo not having responded in months either right at the start of wanting to fork I dont think he's the right person to go forward with anymore. 
As @imario42  has already forked the project and did a release, maybe move that version to an "org" here on github and add maintainers and admins to that org so in case Mario can't keep maintaining the project for whatever reason access isn't lost again and a new fork doesn't have to be made. I agree with the points that @moreaki made, but as I'd really like to use this project I hope a solution will be found soon.

**Comment by chrylis** [comment]
I am still keeping an eye on the project; my bandwidth is limited, but I still want to contribute as I can.

**Comment by imario42** [comment]
@MoxxiManagarm 

A new release 1.1.4 is on its way with Batik updated.

To make the tests run I had to whitelist DOM classes in Rhino can they can be loaded. Like so:
com.openhtmltopdf.visualregressiontests.VisualRegressionTest#whitelistDomClassesInRhino

Didn't find much info about org.apache.batik.script.rhino.RhinoClassShutter and I am not sure if I understood that correctly.
For now it works from an openhtmltopdf perspective and so I am fine with it.
Since this involves a global static list, I did not do that configuration by default. If one needs svg with scripts that whitelisting has to be done.

**Comment by faisalaloraini** [comment]
Thank you @imario42 , for your effort 
I'm facing the below issue after updating to 1.1.4

`Caused by: java.lang.NoClassDefFoundError: org/apache/pdfbox/pdmodel/font/Standard14Fonts$FontName
	at com.openhtmltopdf.pdfboxout.fontstore.AbstractFontStore$BuiltinFontStore.addCourier(AbstractFontStore.java:55)
	at com.openhtmltopdf.pdfboxout.fontstore.AbstractFontStore$BuiltinFontStore.createInitialFontMap(AbstractFontStore.java:43)
	at com.openhtmltopdf.pdfboxout.fontstore.AbstractFontStore$BuiltinFontStore.<init>(AbstractFontStore.java:38)
	at com.openhtmltopdf.pdfboxout.PdfBoxFontResolver.<init>(PdfBoxFontResolver.java:83)
	at com.openhtmltopdf.pdfboxout.PdfBoxRenderer.<init>(PdfBoxRenderer.java:205)
	at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.buildPdfRenderer(PdfRendererBuilder.java:71)
	at com.openhtmltopdf.pdfboxout.PdfRendererBuilder.run(PdfRendererBuilder.java:43)`

**Comment by imario42** [comment]
@faisalaloraini Please ensure you have pdfbox 3.0.0 on your classpath.

**Comment by Viserius** [comment]
@imario42 @kdhrubo What's the latest on this project status matter? Did you manage to make a fork that is actively being maintained and updated? Is the alternative project compatible with PDFBox 3 and Java 21?

**Comment by imario42** [comment]
I forked it and applied the security patches and PDFBox upgrade, but I have no plans to actively maintain the library yet.

Yes, I am using it with PDFBox 3 and Java 21.

`<dependency>
    <groupId>at.datenwort.openhtmltopdf</groupId>
    <artifactId>openhtmltopdf-pdfbox</artifactId>
    <version>1.1.4</version>
</dependency>
`

https://mvnrepository.com/artifact/at.datenwort.openhtmltopdf

https://github.com/danfickle/openhtmltopdf/issues/921#issuecomment-1720870010

**Comment by zachary-foreflight** [comment]
@imario42 I have been evaluating this project for use at my company, and our team has expressed willingness to help maintain the software. 

> With @kdhrubo not having responded in months either right at the start of wanting to fork I dont think he's the right person to go forward with anymore. As @imario42 has already forked the project and did a release, maybe move that version to an "org" here on github and add maintainers and admins to that org so in case Mario can't keep maintaining the project for whatever reason access isn't lost again and a new fork doesn't have to be made. I agree with the points that @moreaki made, but as I'd really like to use this project I hope a solution will be found soon.

Since you have said you aren't planning to actively maintain the project, would you be interested in establishing an openhtmltopdf GitHub organization and transferring ownership of the repo there? This would make it easier for people to find the "official" project which is being actively maintained by the community, and it would help people figure out how to communicate with the maintainers.

If my team is going to invest in this project, I would love to be able to contribute to a stable open-source project rather than a private fork.

My personal GitHub account is @siegelzc BTW.

**Comment by imario42** [comment]
@zachary-foreflight : Sure, lets do that .... erm .... done 😎 !

https://github.com/openhtmltopdf

I invited you as member for now.

**Comment by zacharysiegel** [comment]
@imario42 Can you toggle the repository setting to enable Issues on your repo? or give me permissions to edit the settings? TY

**Comment by daniel-shuy** [comment]
@imario42 could you also make the [openhtmltopdf](https://github.com/openhtmltopdf) organization public?

**Comment by imario42** [comment]
@siegelzc , @zachary-foreflight : I gave your account with 2FA enabled the Owner permissions - and enabled the Issues thing.

@daniel-shuy : Hmmm .. the Org should be public already. At least I can see it without being logged in.

**Comment by daniel-shuy** [comment]
@imario42 somehow the members are not viewable:
<img width="307" alt="image" src="https://github.com/danfickle/openhtmltopdf/assets/17351764/422fd147-eeee-4780-bcbe-4ed9019f1568">

**Comment by imario42** [comment]
@daniel-shuy : Seems each member has to flip the visibility to "public" on their own. I changed mine for now, so at least I am visible now there.
@siegelzc : Maybe you would like to change that for your user too?

**Comment by chrylis** [comment]
@imario42 I'm a little distracted right now, but would you please add me to the org?

**Comment by SalyczeQ** [comment]
our team plan to use this library in bigger project to generate invoices. So we would be happy to help report and also solve the potential issues

**Comment by zacharysiegel** [comment]
> our team plan to use this library in bigger project to generate invoices. So we would be happy to help report and also solve the potential issues

Would you like to be added to the "Friends of Openhtmltopdf" organization?
